from typing import Protocol

from app.domain.assistant import Conversation, Message


class ConversationRepo(Protocol):
    def next_conversation_id(self) -> int: ...

    def next_message_id(self) -> int: ...

    def save(self, conversation: Conversation) -> None: ...

    def get(self, conversation_id: int) -> Conversation | None: ...

    def add_message(self, message: Message) -> None: ...

    def list_for_campaign(self, campaign_id: str) -> list[Conversation]: ...
